version: '3.8'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"  # Selenium Grid
      - "7900:7900"  # VNC access
    volumes:
      - ./chrome_test_profile:/home/seluser/.config/google-chrome
